site_name: KexxuEye Python SDK
theme:
  name: material

nav:
  - Home: index.md
  - API: api.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["src"]
          options:
            docstring_style: google   # or "numpy"
            show_source: true
            separate_signature: true
            filters: ["!^_"]          # hide private members
            inherited_members: true
            show_root_heading: true
            heading_level: 2

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
